### PR TITLE
Required status author validation

### PR DESCRIPTION
**Pull request by justinwyer**
This PR addresses the issue raised in https://github.com/palantir/bulldozer/issues/308

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/bulldozer](https://github.com/palantir/bulldozer), @justinwyer! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by justinwyer** [comment]
Hi there, if there is merit in the issue I opened here is a draft PR that attempts to implement it. This is my first time ever writing in code Go so all critique is welcome :)

**Review by asvoboda — COMMENTED** [review]
It is also worth calling out in the README that this change would require GHE 3.4 at a minimum (IIRC this is when the new API was introduced). That being said, I appreciate that this was implemented in a non breaking way (apologies that my earlier comment implied it wasn't).

**Comment by justinwyer** [comment]
Thanks for pointing out the README changes. I will take a look at the API as well and figure out what version this need, I was working off the assumption that I could use this available since GHE 3.0: https://docs.github.com/en/enterprise-server@3.0/rest/reference/commits#list-commit-statuses-for-a-reference

I have not integration tested this yet, I'll do so on GHE 3.4 for both statuses and checks and if that works I'll try deploy GHE 3.0 and test with that.

**Pull request closed without merging**
