### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by htmldoug**
```
✗ Medium severity issue found in github.com/hashicorp/golang-lru
  Description: MPL-2.0 license
  Info: https://snyk.io/vuln/snyk:lic:golang:github.com:hashicorp:golang-lru:MPL-2.0
  Introduced through: github.com/palantir/go-githubapp/githubapp@0.5.0
  From: github.com/palantir/go-githubapp/githubapp@0.5.0 > github.com/hashicorp/golang-lru@0.5.4

✗ High severity vulnerability found in github.com/dgrijalva/jwt-go
  Description: Access Restriction Bypass
  Info: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMDGRIJALVAJWTGO-596515
  Introduced through: github.com/palantir/go-githubapp/githubapp@0.5.0
  From: github.com/palantir/go-githubapp/githubapp@0.5.0 > github.com/bradleyfalzon/ghinstallation@1.1.1 > github.com/dgrijalva/jwt-go@3.2.0
  Fixed in: 4.0.0-preview1
```

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/bulldozer](https://github.com/palantir/bulldozer), @htmldoug! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by htmldoug** [comment]
Screen Shot 2021-02-02 at 3 31 29 PM

**Comment by htmldoug** [comment]
@derekjobst @asvoboda

**Comment by bluekeyes** [comment]
Hey @htmldoug, thank for updating these. Unfortunately, I think we'll need to hold off on the `go-github v33` upgrade for now. It turns out that this breaks compatibility with the latest versions of GitHub Enterprise (see https://github.com/palantir/policy-bot/pull/261 for details), and Bulldozer also uses the Checks API. Once a compatible version of GitHub Enterprise is out, we can look at upgrading that dependency.

I wonder if it's possible to update the two vulnerable dependencies you flagged without also updating the `go-githubapp` dependency (and therefore `go-github` as well.)

**Comment by htmldoug** [comment]
Thanks for the feedback. I'll give it a shot.

**Comment by derekjobst** [comment]
Thanks @htmldoug!

**Pull request closed without merging**
