### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mojaffar**

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/bulldozer](https://github.com/palantir/bulldozer), @mojaffar! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by mojaffar** [comment]
test

**Comment by asvoboda** [comment]
Hey @mojaffar , did you intend on opening this PR or was it just a test?

**Comment by mojaffar** [comment]
Hi Palantir/Bulldozer,
Actually I need help from end if possible.

I have a requirement to implement auto-merge pull request in my Enterprise
on premises account using this bulldozer bot.

I am requesting you to please help me if possible.

Thanks & Regards,
Mojaffar

**Comment by asvoboda** [comment]
The instructions in the README (https://github.com/palantir/bulldozer#deployment) should be sufficient for deployment. Please open an issue if you have any trouble.

**Pull request closed without merging**
