### PR TITLE
Feature2

### PR DESCRIPTION
**Pull request by brianoh1979**

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/bulldozer](https://github.com/palantir/bulldozer), @brianoh1979! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by asvoboda** [comment]
Hey @brianoh1979,

Was this PR intentional or was it meant to only appear on your fork?

**Comment by brianoh1979** [comment]
Hey Andrew,

Sorry, this was an accident - it was meant to be for my fork!

Thanks for checking in.

I'm trying the Bulldozer utility for a client - in terms of auto merge functionality into say, a Master Branch, should the PR still have to be created to do this auto merge or is the utility meant to do so without creating a PR?

Many Thanks,
Brian.

________________________________

**Comment by asvoboda** [comment]
No worries.

Bulldozer evaluates open Github PRs. It doesn't operate on plain branches. Take a look at the [FAQ](https://github.com/palantir/bulldozer#faq) for other common questions, and feel free to open an issue if you need further help or if something is unclear.

**Pull request closed without merging**
