### PR TITLE
Include commit title when merging PR

### PR DESCRIPTION
**Pull request by coolnalu**
Current logic uses the first commit as the PR title which is often misleading.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/bulldozer/40)

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/bulldozer](https://github.com/palantir/bulldozer), @coolnalu! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by bluekeyes** [comment]
Hey @coolnalu, thanks for the contribution. I'd like to do some testing here before merging to make sure this is appropriate behavior for all of the supported merge types and I'm not sure when that will happen, but just wanted to acknowledge this PR.

I also enabled fork builds in Circle, so I'm going to close and reopen this to trigger a build.

**Comment by coolnalu** [comment]
k will update this when i have a sec later.

**Comment by ajlake** [comment]
Closing out for staleness and also because the entire codebase has churned as part of an app rewrite:
https://github.com/palantir/bulldozer/pull/50

**Pull request closed without merging**
